blank_issues_enabled: false
contact_links:
  - name: Support
    url: ''
    about: Please ask and answer questions here
  - name: Create a proposal
    url: ''
    about: Any requests to create a proposal should go here
