// Ensure NavItems correspond with the MarkDown Content in the same order and similar names
export const NavItems = [
  'Introduction',
  'BTRUST',
  'Delegate',
  'Delegate By Signature',
  'Get Current Votes',
  'Get Prior Votes',
  'Key Events',
  'GovernorAlpha',
  'Quorum Votes',
  'Proposal Threshold',
  'Proposal Max Operations',
  'Voting Delay',
  'Voting Period',
  'Propose',
  'Queue',
  'Execute',
  'Cancel',
  'Get Actions',
  'Get Receipt',
  'State',
  'Cast Vote',
  'Cast Vote With Reason',
  'Cast Vote By Signature',
  'Timelock'
]